name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17  # Use a supported version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Recommended OpenJDK distribution
          java-version: 17
          cache: maven  # Enables caching for Maven dependencies
        
      - name: Build and Test with Maven  # Fixed indentation issue
        run: mvn -B clean verify --file pom.xml


