name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 14
          cache: maven  # Enables dependency caching

      - name: Build and Test with Maven
        run: mvn -B clean verify --file pom.xml

